

#ifndef _CONNECTION_H
#define _CONNECTION_H

enum CONNECTION{NOCONNECTION, NORTH, EAST, SOUTH, WEST, NORTHEAST, NORTHSOUTH,
	EASTSOUTH, NORTHWEST, EASTWEST, SOUTHWEST,
	EASTSOUTHWEST, NORTHSOUTHWEST, NORTHEASTWEST, NORTHEASTSOUTH,
	NORTHEASTSOUTHWEST, CONNECTION_TYPES};

int GetConnectionType(bool n, bool e, bool s, bool w);

#define CONSTRUCTION	0
#define FINISHED		1

#endif