
#ifndef JPSEXPANSION_H
#define JPSEXPANSION_H

#include "../math/vec3i.h"
#include "../math/vec2i.h"
#include "../render/heightmap.h"
#include "../math/vec3f.h"
#include "../math/vec2i.h"
#include "../sys/workthread.h"
#include "../platform.h"

class Unit;
class Building;
class PathNode;

bool Expansion_W(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_E(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_N(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_S(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_NW(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD, 
					const int cmdiag,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_NE(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD, 
					const int cmdiag,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_SW(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD, 
					const int cmdiag,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_SE(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD, 
					const int cmdiag,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_NW_W(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD,
					int runningD2,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_NW_N(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD,
					int runningD2,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_NE_E(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD,
					int runningD2,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_NE_N(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD,
					int runningD2,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_SW_W(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD,
					int runningD2,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_SW_S(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD,
					int runningD2,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_SE_E(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD,
					int runningD2,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

bool Expansion_SE_S(const int cx,
					const int cz,
					const bool roaded, 
					const bool landborne, 
					const bool seaborne, 
					const bool airborne, 
					const Unit* thisu, 
					const Unit* ignoreu, 
					const Building* ignoreb,
					const UnitT* ut,
					WorkThread* wt,
					const int cstartx,
					const int cstartz,
					const int cgoalx, 
					const int cgoalz,
					PathNode* bestS,
					int runningD,
					int runningD2,
					const int cmgoalminx,
					const int cmgoalminz,
					const int cmgoalmaxx,
					const int cmgoalmaxz,
					PathNode** reachedS);

#endif